name: Build pypi package

on:
  push:
    tags: # on tags with versions
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"
          cache: "poetry"
      - name: Install package and dependencies
        run: |
          poetry install --without dev
      - name: Build and publish
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_API_TOKEN }}
