name: Docs Build Test

on:
  push:
    branches:
      - "**" # matches every branch
  pull_request:
    branches: [master]

jobs:
  build:
    # https://github.com/actions/setup-python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run build of docs to see if it works
        run: |
          cd docs
          python -m sphinx -T -E -b html -d build/doctrees -D language=en ./source build/html
